name: Build iOS

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    name: "Build for iOS"

    runs-on: macos-latest

    steps:
      - name: Disable symlinks in git config
        run: git config --global core.symlinks false
        
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: upgrade python and install mako
        run: |
           python -m pip install --upgrade pip
           pip install mako

      - name: Build
        run: |
          brew install meson pkg-config
          git clone --depth 1 https://github.com/KhronosGroup/MoltenVK
          ln -s vulkan_ios.pc vulkan.pc
          meson setup "build-ios" \
            --prefix=/tmp/zink \
            --cross-file ios-aarch64 \
            -Dmoltenvk-dir=../../../../MoltenVK/MoltenVK \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=swrast,zink \
            -Dshared-glapi=false
          ninja -C "build-ios" install
          install_name_tool -change /tmp/zink/lib/libglapi.0.dylib @executable_path/Frameworks/libglapi.0.dylib.framework/libglapi.0.dylib -add_rpath @executable_path/Frameworks/libMoltenVK.dylib.framework /tmp/zink/lib/libOSMesa.8.dylib
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libzink_${{matrix.arch}}
          path: /tmp/zink
